export const ABOUT_ME = `Hi there! My name is Spencer and I’m a Front-end Web developer with a passion for building User Interfaces and all things tech. In my free time, I enjoy spending time with my wife and our 4 dogs, as well as playing guitar and exploring the world. I am also a lover of science and enjoy learning about all manner of nerdy topics.`;

// Mostly generated by https://www.feedough.com/about-me-generator/
export const ABOUT_ME_EXTENDED = `Born and raised in Silicon Valley during the 90s, I witnessed the evolution of the Internet from its humble beginnings to its explosive growth. My journey in web development started before the advent of CSS and even the <code>font</code> attribute! It's been a wild ride, experiencing the rise, fall, and resurgence of the Internet.

Integrity and transparency are at the core of everything I do. I believe in doing things the right way, even when no one is watching. When I'm not immersed in the digital realm, I find solace in traveling the world with my wife or playing with our 4 dogs. Cooking has always been a cherished pastime for me, offering an opportunity to indulge in the joys of good food and great company. Alongside these passions, I feed my soul with music, channeling my energy and emotions through my guitar. Beyond music, I seek adventure through kayaking and rock climbing, constantly pushing the boundaries of my physical and mental capabilities. To put it simply, I draw inspiration from the world around me, both terrestrial and beyond.

Looking ahead, I am excited to continue honing my skills as a web developer and embracing new opportunities for growth and creativity in the digital space. I aspire to create meaningful experiences that leave a lasting impression on users while also constantly exploring new professional avenues and expanding my knowledge.

But above all, I strive to approach life with curiosity and open-mindedness. I believe that every experience, every interaction, is an opportunity for growth. I'm excited to see where this journey takes me next.
`;
